dataset:
  name: PDE_KS
  pair_id: [1]
model:
  name: spacetime
  lag: 336
  horizon: 336
  embedding_config: "embedding/repeat"
  encoder_config: "encoder/default_no_skip"
  decoder_config: "decoder/default"
  output_config: "output/default"
  kernel_dim: 64
  norm_order: 1
  batch_size: 5
  dropout: 0.25
  mlp_n_layers: 1
  n_blocks: 3
  lr: 8.68e-5
  weight_decay: 0.0001
  max_epochs: 200
  early_stopping_epochs: 20
  data_transform: "mean"
  loss: "informer_rmse"
  val_metric: "informer_rmse"
  criterion_weights: [1, 1, 1]
  seed: 0
  no_wandb: True