dataset:
  name: PDE_KS
  pair_id: [12]
model:
  name: spacetime
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 2
  embedding_config: embedding/repeat
  encoder_config: encoder/default_no_skip
  decoder_config: decoder/default
  output_config: output/default
  mlp_n_layers: 1
  norm_order: 1
  batch_size: 5
  early_stopping_epochs: 20
  data_transform: mean
  loss: informer_rmse
  val_metric: informer_rmse
  max_epochs: 200
  criterion_weights:
    - 1
    - 1
    - 1
  no_wandb: True
hyperparameters:
  lag:
    type: choice
    choices: [336, 720]
  horizon:
    type: choice
    choices: [96, 192, 336, 720]
  n_blocks:
    type: choice
    choices: [3,4,5,6]
  weight_decay:
    type: choice 
    choices: [0, 0.0001]
  kernel_dim:
    type: choice
    choices: [32,64,128]
  dropout:
    type: choice
    choices: [0.0, 0.25]
  lr:
    type: loguniform
    lower_bound: 0.00001
    upper_bound: 0.001
