dataset:
  name: ODE_Lorenz
  pair_id: [8]
model:
  name: spacetime
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 2
hyperparameters:
  lag:
    type: randint
    lower_bound: 5
    upper_bound: 45
  horizon:
    type: randint
    lower_bound: 15
    upper_bound: 100
  n_blocks:
    type: randint
    lower_bound: 3
    upper_bound: 6
  weight_decay:
    type: choice 
    choices: [0, 0.0001]
  lr:
    type: loguniform
    lower_bound: 0.01
    upper_bound: 0.001
  dropout:
    type: choice
    choices: [0.1, 0.2]
