dataset:
  name: PDE_KS
model:
  name: CTF_NaiveBaselines
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 10
hyperparameters:
  constant:
    type: uniform
    lower_bound: -1.0
    upper_bound: 1.0
