dataset:
  name: ODE_Lorenz
  pair_id: [8]
model:
  name: spacetime
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 2
  embedding_config: embedding/repeat
  encoder_config: encoder/default_no_skip
  decoder_config: decoder/default
  output_config: output/default
  mlp_n_layers: 1
  kernel_dim: 64
  norm_order: 1
  batch_size: 5
  early_stopping_epochs: 2
  data_transform: mean
  loss: informer_rmse
  val_metric: informer_rmse
  max_epochs: 2
  criterion_weights:
    - 1
    - 1
    - 1
  no_wandb: True
hyperparameters:
  lag:
    type: randint
    lower_bound: 5
    upper_bound: 15
  horizon:
    type: randint
    lower_bound: 5
    upper_bound: 15
  n_kernels:
    type: choice
    choices: [8, 16, 32, 64, 128]
  n_blocks:
    type: randint
    lower_bound: 3
    upper_bound: 6
  weight_decay:
    type: choice 
    choices: [0, 0.0001]
  lr:
    type: loguniform
    lower_bound: 0.0001
    upper_bound: 0.01
  dropout:
    type: choice
    choices: [0.1, 0.2]
